services:
  app:
    image: myportfolio
    build:
      args:
        - target=dev
    environment:
      PORTFOLIO_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"
